- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Install nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  register: nginx_conf

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
    enabled: true
